[project]
name = "music-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "fastapi[standard]>=0.115.12",
    "pip>=25.1.1",
    "requests>=2.32.3",
    "uvicorn>=0.34.2",
]
